#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__
// App Delegate
#define SCEEN_WIDTH 800
#define SCEEN_HEIGHT 800
#define PI 3.14159265

// Splash Sceen
#define DISPLAY_TIME_SPLASH_SCEEN 2
#define TRANSITION_TIME 0.5

// Main Menu Scene

// Game Scene
#define PLAYER_COLLISION_BITMASK 1000
#define BULLET_COLLISION_BITMASK 1001
#define TRAP_COLLISION_BITMASK 1002
#define MINE_BOMB_COLLISION_BITMASK 1003
#define TREASURE_COLLISION_BITMASK 1004
#define COIN_COLLISION_BITMASK 2000
#define MUSIC_BOX_COLLISION_BITMASK 3001
#define BOSS_COLLISION_BITMASK 3000
#define PLAYER_TAG 1
#define MONSTER_TAG 10
#define MONSTER_LIMIT 20
#define COIN_LIMIT 50
#define MINE_LIMIT 20
#define TRAP_LIMIT 20
#define BOSS_COUNT 500000

#endif // __DEFINITIONS_H__
